### ISSUE TITLE
clean project .vscode should not be tracked

### ISSUE THREAD

**Issue by smeerws** [4ahmnm2021-G3-G4/01-maze-audiocode-dejan01#1]
https://github.com/HTL-SBG/FAQIssuesUnityVSGitGitHub/issues/1

**Comment by Dejan01** [comment]
Can't push change

**Comment by smeerws** [comment]
I need more info, what is the error?

**Comment by Dejan01** [comment]
Ich hab den .vscode folder mit dem Befehl "git rm -r --cached folderToUntrack" untracked. Im Terminal wird dann .vscode grün angezeigt. Muss ich es dann commttten und pushen? Ich habs zwar gemacht, in meinem Repo auf Github wird aber nichts angezeigt

**Comment by smeerws** [comment]
Solange grün ist es in der stage area, gehört commited dann gepushed

Dejan01 ***@***.***> schrieb am Mi., 23. Juni 2021, 12:44:
